source "https://rubygems.org"

ruby ">= 3.1"

# Resend SDK
gem "resend", "~> 1.0"

# Environment variables
gem "dotenv", "~> 3.0"

# Web frameworks
gem "sinatra", "~> 4.0"
gem "sinatra-contrib", "~> 4.0"
gem "puma", "~> 6.4"
gem "rack", "~> 3.0"

# JSON parsing
gem "json", "~> 2.7"
