source "https://rubygems.org"

ruby ">= 3.1"

# Rails API
gem "rails", "~> 8.0"
gem "puma", "~> 7.2", ">= 7.2.1"

# Resend SDK
gem "resend", "~> 1.0"

# Environment variables
gem "dotenv-rails", "~> 3.0"
