version: "3.4"

services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      RESEND_API_KEY: ${RESEND_API_KEY}
    networks:
      - default
    volumes:
      - .:/app
    command: "bundle exec ruby app.rb"